### ISSUE TITLE
Exception in task_file_mover when ingressing files since Shipyard upgrade to 3.7.1

### ISSUE THREAD

**Issue by f-roche** [Azure/batch-shipyard#296]
Hi,
I am having an exception when ingressing files from another task. I have this issue since the upgrade I did from Batch-Shipyard 3.6.0 to 3.7.1.

Here is the exception I got in the `stdout.txt` file of the task when running the `alfpark/batch-shipyard:3.7.1-cargo` docker image at task startup:
```
Traceback (most recent call last):
  File "/opt/batch-shipyard/task_file_mover.py", line 173, in <module>
    main()
  File "/opt/batch-shipyard/task_file_mover.py", line 148, in main
    batch_client = _create_credentials()
  File "/opt/batch-shipyard/task_file_mover.py", line 65, in _create_credentials
    batchauth.SharedKeyCredentials(ba, bakey), base_url=url)
TypeError: __init__() got an unexpected keyword argument 'base_url'
```

It looks like the call to `SharedKeyCredentials` is failing because recent version of `azure-batch` python package changed its constructor parameters (v6.0.0):
[Python Azure-Batch package releases](https://pypi.org/project/azure-batch/)
`Breaking Renamed the base_url parameter to batch_url on BatchServiceClient class, and it is required now.`

**Comment by f-roche** [comment]
Here are the changes to apply on `Cargo`:
![image](https://user-images.githubusercontent.com/10049032/62295899-565f5000-b46e-11e9-8e3f-23e791287a3c.png)

**Comment by f-roche** [comment]
I can create a pull request if you want, but it looks like I don't have the permission to create branches, right?

**Comment by f-roche** [comment]
after some investigations, it looks like you already fixed it in `cbb3689` commit but you did not merge it to your latest release 3.7.1... could you integrate it into a new maintenance release as it affects 3.7.0 and 3.7.1 releases?

**Comment by alfpark** [comment]
`3.7.0` was fixed in-situ via manual build and push to Docker Hub (#274). I've done the same for `3.7.1`; it was erroneously missed in the release. Please let me know if your issue is fixed.

The fix will be included properly in `3.8.0` or the next hotfix release.
